baseURL = 'https://sleepybyt.es/'
languageCode = 'en-us'
title = 'Sleepy Bytes'
author = 'Aaron Huang'
copyright = "Copyright © 2023, Sleepy Bytes."
theme = 'hugo-bearblog'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true
[params]
  # Site description
  description = 'A lethargic approach to all things tech.'
  # Hide made with hugo line
  hideMadeWithLine = true

[taxonomies]
  tag = "tags"
